### ISSUE TITLE
AR_HOMOPHONES_REPLACE: عدم الاعتماد على السياق يؤدي لنتائج false positive 

### ISSUE THREAD

**Issue by muotaz** [sohaibafifi/languagetool#83]
السلام عليكم 

أود مناقشة  موضوع ظهر أثناء تجربة دمج كود LT للغة العربية مع نظام تدقيق إملائي أعمل عليه، وهو أن  قواعد AR_HOMOPHONES_REPLACE أحياناً تولد نتائج false positive أثناء التدقيق بسبب عدم الاعتماد على السياق لإزالة الشك disambiguation.
مثلاً عند تدقيق نص قانوني علّمت الأداة كلمة **ضمان** بأنها خطأ وعرضت بديل لها كلمة **ظمآن**.

فما السبيل اﻷمثل برأيكم لحل هذا الإشكال ؟ مستعد للمساهمة بالبرمجة أيضاً ولو أن مهاراتي بالجافا تحتاج إلى صقل قليلاً.

**Comment by linuxscout** [comment]
السلام عليكم،
هذه القاعدة لا تعتبر الكلمات خاطئة، بل تذكر المستخدم إلى وجود كلمات لها نفس الشكل، قد يلتبس في كتابتها،
مثلا بعضهم لديه مشكلة في ضبط الضاد والظاء، وهذه القاعدة، تعرض الكلمتين للتحقق،
بعد مراجعتي للأمر، ظهر أنّ رسالة الخطأ غير مضبوطة.، لذا زادت الأمر التباسا

**Comment by muotaz** [comment]
السلام عليكم أستاذ طه؛

شكراً لك. سوف أغلق هذه البطاقة.
