### ISSUE TITLE
سؤال: ما الفرق بين rules.csv و grammar.xml 

### ISSUE THREAD

**Issue by muotaz** [sohaibafifi/languagetool#86]
السلام عليكم أيها الأساتذة 

ما الفرق بين ملفي rules.csv و grammar.xml ؟ 
لقد بحثت عن بعض القواعد من ملف rules.csv في بقية ملفات الموارد في مجلد اللغة العربية في الكود ولم أجدها في الملفات المصدرية. 

شكراً لكم سلفاً

**Comment by linuxscout** [comment]
الملف rules.csv  ملف نصي فيه قواعد خام، وضعنا فيه بعض الأخطاء اللغوية، بصيغة قل ولا تقل،
هذه القواعد تحتاج إلى نمذجة وبرمجة لتحويلها إلى صيغة يفهمها البرنامج،
يمكن اعتباره ملف بيانات أو توثيق.

**Comment by muotaz** [comment]
إذا الملف الأساسي هو grammar.xml حيث تكمن القواعد المنمذجة. 
شكراً جزيلاً

**Comment by linuxscout** [comment]
تجد بيانات وموارد في مستودع
https://github.com/linuxscout/fareh
